version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./table-with-procedure.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - network

  webapp:
    build:
      context: .
      dockerfile: Dockerfile.webapp
    container_name: webapp-container
    ports:
      - "80:80"
    environment:
      - DB_URL=jdbc:mysql://mysql-container:3306/courseSelect
      - DB_USERNAME=root
      - DB_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - network

networks:
  network:
    driver: bridge
